steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.' ]
- name: node:10.15.1
  entrypoint: npm
  args: [ 'install' ]
- name: node:10.15.1
  entrypoint: npm
  args: [ 'test' ]
- name: node:10.15.1
  entrypoint: npm
  args: [ 'install' ]
  dir: './functions/functions'
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: [ 'deploy', '--deploy', '-P', '${_PROJECT_ID_TARGET}${_FIREBASE_COMPONENT}', '--token', '$_FIREBASE_TOKEN']
  dir: '$_FIREBASE_COMPONENT'
